### ISSUE TITLE
pro tip: responsivitat

### ISSUE THREAD

**Issue by Samitier** [miquelalcon/mean#9]
Per a la responsivitat, que no n'hem parlat gens, et recomano molt que triis diferents "break points" per la teva app abans de començar a estilar res i te'ls deixis a `variables.less`. Sinó aniràs fent media queries amb valors de widths aleatoris i et tornaràs boig, millor estandaritzar-ho i cenyir-te a unes mides concretes.

Un break point vindrien a ser els diferents tamanys de pantalla més comuns on la interfície ha de quedar bé. Gairebé sempre agafo els de [bootstrap 4](https://v4-alpha.getbootstrap.com/layout/overview/). Segurament ja coneixes aquest framework, és súper útil per a fer dissenys responsive fàcilment i els seus breakpoints gairebé s'han tornat un estàndar.

Els seus breakpoints son els següents, te'ls pots declarar així al less:
```less
@xs: 0px;
@sm: 576px;
@md: 768px;
@lg: 992px;
@xl: 1200px;

// Small devices (landscape phones, 576px and up)
@media (min-width: @sm) { ... }
// Medium devices (tablets, 768px and up)
@media (min-width: @md) { ... }
// Large devices (desktops, 992px and up)
@media (min-width:@lg) { ... }
// Extra large devices (large desktops, 1200px and up)
@media (min-width: @xl) { ... }
```
Un altre framework que et recomano com alternativa a bootstrap es [flexboxgrid](http://flexboxgrid.com/). Súper lightweight i fàcil de fer servir.
